name: Sync Fork with Upstream

on:
  schedule:
    - cron: "0 3 * * *" # 每天凌晨3点（UTC）自动运行
  workflow_dispatch: # 手动触发 workflow_dispatch	支持你在 GitHub 网页上手动触发同步

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 允许推送代码

    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # 原始仓库信息
      # upstream 仓库用于同步最新的主项目代码到当前 fork，确保 fork 保持更新
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/ahpxex/open-dictionary.git
          git fetch upstream

      - name: Create release branch if not exists
        run: |
          git checkout master
          git checkout -b release || git checkout release

      # 避免交互式合并信息
      # main	目标分支（如果是 dev、release 等分支，请改名）
      - name: Merge upstream master into release
        run: |
          git checkout release
          git merge upstream/master --no-edit || echo "Merge failed due to conflicts or errors. Please check the logs for details."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # GITHUB_TOKEN	GitHub 自动提供，无需额外配置权限

      - name: Push changes to fork
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} release
